source :gemcutter

gem "foreman"
gem "unicorn"
gem "thin" 
gem "sinatra", :git => "git://github.com/sinatra/sinatra.git"

gem "rake"

# If you use New relic
#gem "newrelic_rpm"

# If you want to debug your code
#gem "ruby-debug19"

#gem "bcrypt-ruby", "3.0.1"
#gem "mime-types", "1.19"

gem "ysd_yito",">= 0.1.7" # The yito base

# Models
gem "ysd_md_rac", ">= 0.2.0" 
gem "ysd_md_attachment", ">= 0.2.0"
gem "ysd_md_audit",">= 0.2.0"
gem "ysd_md_mail",">= 0.2.0"
gem "ysd_md_cms",">= 0.2.0"
gem "ysd_md_photo_gallery",">= 0.2.0"
gem "ysd_md_profile", ">= 0.2.0"
gem "ysd_md_business_events", ">= 0.2.0"
gem "ysd_md_integration", ">= 0.2.0"
gem "ysd_md_configuration", ">= 0.2.0"
gem "ysd_md_fieldset", ">= 0.2.0"
gem "ysd_md_system", ">= 0.2.0"
gem "ysd_md_comparison", ">= 0.2.0"
gem "ysd_md_logger", ">= 0.2.0" 
gem "ysd_md_translation", ">= 0.2.0"
gem "ysd_md_location", ">= 0.2.0"

# Plugins
gem "ysd_plugin_aspects",">= 0.1"
gem "ysd_plugin_audit",">= 0.1"
gem "ysd_plugin_auth",">= 0.1"
gem "ysd_plugin_profile",">= 0.1"
gem "ysd_plugin_cms",">= 0.1"
gem "ysd_plugin_community",">= 0.1"
gem "ysd_plugin_configuration", ">= 0.1"
gem "ysd_plugin_contact",">= 0.1"
gem "ysd_plugin_integration", ">= 0.1"
gem "ysd_plugin_location", ">= 0.1"
gem "ysd_plugin_media_gallery", ">= 0.1"
gem "ysd_plugin_system", ">= 0.1"
gem "ysd_plugin_mail",">= 0.1"
gem "ysd_plugin_forum",">= 0.1"
gem "ysd_plugin_education_employment",">= 0.1"
gem "ysd_plugin_hobbies",">= 0.1"
gem "ysd_plugin_rca",">= 0.1"
gem "ysd_plugin_translation",">= 0.1"
gem "ysd_plugin_attachment",">= 0.1"
gem "ysd_plugin_event",">= 0.1"
gem "ysd_plugin_errors", ">= 0.1"
gem "ysd_plugin_language", ">= 0.1"
gem "ysd_plugin_background", ">= 0.1"

# If your application stores data on mongodb, uncomment the following lines
gem "mongo"
gem "bson"
gem "bson_ext"

# If you want to store data on yaml, uncomment the following line
#gem "dm-yaml-adapter","1.2.0"

# If your application stores data on postgreSQL database, uncomment the following lines
gem "do_postgres","0.10.8"
gem "dm-postgres-adapter","1.2.0"
gem "pg","0.13.2"
