name: Default
description: Default theme. It uses 960.css
styles: [
    '/css/style.css',
    'http://fonts.googleapis.com/css?family=Cutive+Mono|Open+Sans:400italic,400,800,700,600'
    ]
scripts: []
images: []
regions: ['top', 'header', 'languages_translation', 'login_register', 
          'connected_user', 'container_header', 'container_headline', 
          'content_top', 'content_left', 'content_right', 'content_bottom',
          'container_bottom', 'bottom']
